### ISSUE TITLE
Functionality to add swagger support

### ISSUE THREAD

**Issue by Akayeshmantha** [cloudspex/cloudAI#10]

**Comment by DDevinda** [comment]
I did a small research about swagger. Swagger UI provide users ability to visualize APIs without having any implementation from developers side. We can simply use swagger editor to design APIs and designers can host their APIs in SwaggerHub. There are two main approaches to develop APIs. First one is design first and second one is code first. Code first is a traditional approach and design first is somewhat new approach. 
Code First: First we identify the issues and we code API first and then we create swagger document.
Design First: First we identify the issues and we create the swagger document and then from that swagger document, we build the API
Since we need good communication with users, i think we should go with code first approach. Because a good documentation is a good success and it can adopt more users.
